learning_blog/learning_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_blogs.urls')),
]

learning_blog/learning_blogs/urls.py
"""定义learning_blogs的URL模式"""

from django.urls import path

from . import views

app_name = 'learning_blogs'
urlpatterns = [
	# 主页
    path('', views.index, name='index'),
	# 显示所有的博客标题
    path('blogposts/', views.blogposts, name='blogposts'),
	# 显示特定博客的博文内容
    path('blogposts/<int:blogpost_id>/', views.blogpost, name='blogpost'),
	# 用于添加新博客的页面
    path('new_blogpost/', views.new_blogpost, name='new_blogpost'),
	# 用于添加新博文的页面
    path('new_blogartical/<int:blogpost_id>/', views.new_blogartical, name='new_blogartical'),
	# 用于编辑博文的页面
    path('edit_blogartical/<int:blogartical_id>/', views.edit_blogartical, name='edit_blogartical'),
]

learning_blog/users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# 包含默认的身份验证URL
    path('', include('django.contrib.auth.urls')),
	# 注册页面
    path('register/', views.register, name='register'),
]

learning_blog/learning_blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
	"""博客的字段定义"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""返回博客的标题"""
		return self.text

class BlogArtical(models.Model):
	"""博文的字段定义"""
	blogPost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
    
	class Meta:
		verbose_name_plural = 'blogarticales'
 
	def __str__(self):
		"""返回博文的内容"""
		return f"{self.text[:50]}..."

learning_blog/users/models.py
from django.db import models

# Create your models here.

learning_blog/learning_blogs/forms.py
from django import forms

from .models import BlogPost,BlogArtical

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text': ''}

class BlogArticalForm(forms.ModelForm):
    class Meta:
        model = BlogArtical
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_blog/learning_blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost, BlogArtical
from .forms import BlogPostForm, BlogArticalForm

def index(request):
	"""博客的主页"""
	return render(request, 'learning_blogs/index.html')

@login_required
def blogposts(request):
	"""显示所有的博客"""
	blogposts = BlogPost.objects.filter(owner=request.user).order_by('date_added')
	context = {'blogposts': blogposts}
	return render(request, 'learning_blogs/blogposts.html', context)

@login_required
def blogpost(request, blogpost_id):
	"""显示单个博客及其所有的内容"""
	blogpost = BlogPost.objects.get(id=blogpost_id)
	if blogpost.owner != request.user:
		raise Http404

	blogarticals = blogpost.blogartical_set.order_by('-date_added')
	context = {'blogpost': blogpost, 'blogarticals': blogarticals}
	return render(request, 'learning_blogs/blogpost.html', context)

@login_required
def new_blogpost(request):
	"""添加新博客"""
	if request.method != 'POST':
		form = BlogPostForm()
	else:
		form = BlogPostForm(data=request.POST)
		if form.is_valid():
			new_blogpost = form.save(commit=False)
			new_blogpost.owner = request.user
			new_blogpost.save()
			return redirect('learning_blogs:blogposts')

	context = {'form': form}
	return render(request, 'learning_blogs/new_blogpost.html', context)

@login_required
def new_blogartical(request, blogpost_id):
	"""在特定的博客添加新博文"""
	blogpost = BlogPost.objects.get(id=blogpost_id)
    
	if request.method != 'POST':
		form = BlogArticalForm()
	else:
		form = BlogArticalForm(data=request.POST)
		if form.is_valid():
			new_blogartical = form.save(commit=False)
			new_blogartical.blogpost = blogpost
			new_blogartical.save()
			return redirect('learning_blogs:blogpost', blogpost_id=blogpost_id)

	context = {'blogpost': blogpost, 'form': form}
	return render(request, 'learning_blogs/new_blogartical.html', context)

@login_required
def edit_blogartical(request, blogartical_id):
	"""编辑既有博文"""
	blogartical = BlogArtical.objects.get(id=blogartical_id)
	blogpost = blogartical.blogpost
	if blogpost.owner != request.user:
		raise Http404
    
	if request.method != 'POST':
		form = BlogArticalForm(instance=blogartical)
	else:
		form = BlogArticalForm(instance=blogartical, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('learning_blogs:blogpost', blogpost_id=blogpost.id)

	context = {'blogartical': blogartical, 'blogpost': blogpost, 'form': form}
	return render(request, 'learning_blogs/edit_blogartical.html', context)
	

learning_blog/users/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单   
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            login(request, new_user)
            return redirect('learning_blogs:index')

    # 显示空表单或指出表单无效
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_blog/learning_blogs/templates/learning_blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning Blog</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_blogs:index'%}">
        Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_blogs:blogposts'%}">
              Blogposts</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

learning_blog/learning_blogs/templates/learning_blogs/blogpost.html
{% extends 'learning_blogs/base.html' %}

{% block content %}

  <p>BlogPost: {{ blogpost }}</p>

  <p>博文</p>
  <p>
    <a href="{% url 'learning_blogs:new_blogartical' blogpost.id %}">添加新的博文</a>
  </p>

  <ul>
  {% for blogartical in blogarticals %}
    <li>
      <p>{{ blogartical.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ blogartical.text|linebreaks }}</p>
      <p>
        <a href="{% url 'learning_blogs:edit_blogartical' blogartical.id %}">编辑博文</a>
      </p>
    </li>
  {% empty %}
    <li>这个博客还没有内容哦</li>
  {% endfor %}
  </ul>

{% endblock content %}

learning_blog/learning_blogs/templates/learning_blogs/blogposts.html
{% extends "learning_blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h1>这里展示你的博客</h1>
{% endblock page_header %}

{% block content %}
	<ul>
		{% for blogpost in blogposts %}
			<div class="card mb-3">
				<h4 class="card-header">
					{{ blogpost.date_added|date:'M d,Y H:i' }}
				<small><a href="{% url 'learning_blogs:new_blogpost' %}">
						添加一个新的博客</a></small>
				</h4>
				<div class="card-body">
					<a href="{% url 'learning_blogs:blogpost' blogpost.id %}">{{ blogpost }}</a>
				</div>
			</div>
		{% empty %}
		  <div class="alert alert-secondary" role="alert">
			还没有博客，快去创建你的第一个博客吧!
		  </div>
		  <h3><a href="{% url 'learning_blogs:new_blogpost' %}">添加一个新的博客</a></h3>
		{% endfor %}
	</ul>

{% endblock content %}

learning_blog/learning_blogs/templates/learning_blogs/edit_blogartical.html
{% extends 'learning_blogs/base.html' %}

{% block content %}
	<p><a href="{% url 'learning_blogs:blogpost' blogpost.id%}">{{ blogpost }}</a></p>	
	
	
	<p>编辑你的博文</p>
	
	<form action="{% url 'learning_blogs:edit_blogartical' blogpost.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">保存修改</button>		
	</form>

{% endblock content %}

learning_blog/learning_blogs/templates/learning_blogs/index.html
{% extends "learning_blogs/base.html" %}

{% block page_header %}
	<div class="jumbotorn">
		<h1 class="display-3">记录你的博客</h1>
		
		<p class="lead">在这里你可以记录你的生活日常</p>
		
		<a class="btn btn-lg  btn-primary" href="{% url 'users:register' %}"
			role="button">注册 &raquo</a>			
	</div>
{% endblock page_header %}

learning_blog/learning_blogs/templates/learning_blogs/new_blogartical.html
{% extends 'learning_blogs/base.html' %}

{% block content %}
	<p><a href="{% url 'learning_blogs:blogpost' blogpost.id%}">{{ blogpost }}</a></p>	
	<p>添加一个新的博文</p>
	<form action="{% url 'learning_blogs:new_blogartical' blogpost.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">添加博文</button>		
	</form>

{% endblock content %}

learning_blog/learning_blogs/templates/learning_blogs/new_blogpost.html
{% extends 'learning_blogs/base.html' %}

{% block content %}
	<p>添加一个博客</p>
	
	<form action="{% url 'learning_blogs:new_blogpost' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">添加博客</botton>		
	</form>

{% endblock content %}