learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_log/learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path

from . import views

app_name ='learning_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 显示所有主题
    path('topics/', views.topics, name='topics'),
    # 特定主题的详细页面
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 用于添加新主题的页面
    path('new_topic/', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # 显示所有教师
    path('teachers/', views.teachers, name='teachers'),
    # 特定教师的详细页面
    path('teachers/<int:teacher_id>/', views.teacher, name='teacher'),
    # 用于添加新教师的页面
    path('new_teacher/', views.new_teacher, name='new_teacher'),
    # 用于添加新教师详情的页面
    path('new_teacherMessage/<int:teacher_id>/', views.new_teacherMessage, name='new_teacherMessage'),
    # 用于编辑教师详情的页面
    path('edit_teacherMessage/<int:teacherMessage_id>/', views.edit_teacherMessage, name='edit_teacherMessage'),
    # 用于删除教师详情的页面
    path('delete_teacherMessage/<int:teacherMessage_id>/', views.delete_teacherMessage, name='delete_teacherMessage'),
]

learning_log/users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path,include

from . import views

app_name = 'users'
urlpatterns = [
    # 包含默认的的身份验证URL
    path('', include('django.contrib.auth.urls')),
	# 注册页面
    path('register/', views.register, name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text


class Teacher(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class TeacherMessage(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'teacherMessages'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

learning_log/learning_logs/forms.py
from django import forms

from .models import Topic,Entry,Teacher,TeacherMessage

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ' '}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name']
        labels = {'name': ''}


class TeacherMessageForm(forms.ModelForm):
    class Meta:
        model = TeacherMessage
        fields = ['text']
        labels = {'text': ' '}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry,Teacher,TeacherMessage
from .forms import TopicForm, EntryForm,TeacherForm,TeacherMessageForm

def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def teachers(request):
    """Show all teachers."""
    teachers = Teacher.objects.filter(owner=request.user).order_by('date_added')
    context = {'teachers': teachers}
    return render(request, 'learning_logs/teachers.html', context)


@login_required
def teacher(request, teacher_id):
    """Show a single teacher and all its teacherMessages."""
    teacher = Teacher.objects.get(id=teacher_id)
    # Make sure the teacher belongs to the current user.
    if teacher.owner != request.user:
        raise Http404

    teacherMessages = teacher.teachermessage_set.order_by('-date_added')
    context = {'teacher': teacher, 'teacherMessages': teacherMessages}
    return render(request, 'learning_logs/teacher.html', context)


@login_required
def new_teacher(request):
    """Add a new teacher."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TeacherForm()
    else:
        # POST data submitted; process data.
        form = TeacherForm(data=request.POST)
        if form.is_valid():
            new_teacher = form.save(commit=False)
            new_teacher.owner = request.user
            new_teacher.save()
            return redirect('learning_logs:teachers')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_teacher.html', context)


@login_required
def new_teacherMessage(request, teacher_id):
    """Add a new teacherMessage for a particular teacher."""
    teacher = Teacher.objects.get(id=teacher_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TeacherMessageForm()
    else:
        # POST data submitted; process data.
        form = TeacherMessageForm(data=request.POST)
        if form.is_valid():
            new_teacherMessage = form.save(commit=False)
            new_teacherMessage.teacher = teacher
            new_teacherMessage.save()
            return redirect('learning_logs:teacher', teacher_id=teacher_id)

    # Display a blank or invalid form.
    context = {'teacher': teacher, 'form': form}
    return render(request, 'learning_logs/new_teacherMessage.html', context)


@login_required
def edit_teacherMessage(request, teacherMessage_id):
    """Edit an existing teacherMessage."""
    teacherMessage = TeacherMessage.objects.get(id=teacherMessage_id)
    teacher = teacherMessage.teacher
    if teacher.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current teacherMessage.
        form = TeacherMessageForm(instance=teacherMessage)
    else:
        # POST data submitted; process data.
        form = TeacherMessageForm(instance=teacherMessage, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:teacher', teacher_id=teacher.id)
    context = {'teacherMessage': teacherMessage, 'teacher': teacher, 'form': form}
    return render(request, 'learning_logs/edit_teacherMessage.html', context)


@login_required
def delete_teacherMessage(request, teacherMessage_id):
    """Delete an existing teacherMessage."""
    teacherMessage = TeacherMessage.objects.get(id=teacherMessage_id)
    teacher = teacherMessage.teacher
    if teacher.owner != request.user:
        raise Http404

    if request.method == 'POST':
        # POST data submitted; delete the teacherMessage.
        teacherMessage.delete()
        return redirect('learning_logs:teacher', teacher_id=teacher.id)

    context = {'teacherMessage': teacherMessage, 'teacher': teacher}
    return render(request, 'learning_logs/delete_teacherMessage.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning Log</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
        Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">
              Topics</a></li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:teachers'%}">
              Teachers</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

learning_log/learning_logs/templates/learning_logs/delete_teacherMessage.html
<!-- delete_teacherMessage.html -->
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>你确定删除么</h2>
{% endblock page_header %}

{% block content %}
    <p>{{ teacherMessage.message }}</p>
    <form action="{% url 'learning_logs:delete_teacherMessage' teacherMessage.id %}" method='post' class="form">
        {% csrf_token %}
        {% buttons %}
            <button name='submit' class="btn btn-danger">是的，确认删除</button>
            <a href="{% url 'learning_logs:teacher' teacher.id %}" class="btn btn-secondary">不，返回刚刚的页面</a>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
	<h3>Edit entry:</h3>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
	{% buttons %}
		<button name="submit" class="btn btn-primary">Save changes</button>
	{% endbuttons %}
  </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_teacherMessage.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2><a href="{% url 'learning_logs:teacher' teacher.id %}">{{ teacher }}</a></h2>
	<h3>Edit teacherMessage:</h3>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:edit_teacherMessage' teacherMessage.id %}" method="post" class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
	{% buttons %}
		<button name="submit" class="btn btn-primary">Save changes</button>
	{% endbuttons %}
  </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the
        topics you're learning about. Whenever you learn something new
        about a topic, make an entry summarizing what you've learned.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
	<h3>Add a new entry:</h3>
{% endblock page_header %}

{% block content %}
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name='submit' class="btn btn-primary">Add entry</button>
		{% endbuttons %}
	</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_teacher.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2>Add a new teacher：</h2>
{% endblock page_header %}

{% block content %}
	<form action="{% url 'learning_logs:new_teacher' %}"method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-primary">Add teacher</button>
		{% endbuttons %}
		
	</form>
	

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_teacherMessage.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2><a href="{% url 'learning_logs:teacher' teacher.id %}">{{ teacher }}</a></h2>
	<h3>Add a new teacherMessage:</h3>
{% endblock page_header %}

{% block content %}
	<form action="{% url 'learning_logs:new_teacherMessage' teacher.id %}" method='post' class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name='submit' class="btn btn-primary">Add teacherMessage</button>
		{% endbuttons %}
	</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2>Add a new topic：</h2>
{% endblock page_header %}

{% block content %}
	<form action="{% url 'learning_logs:new_topic' %}"method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-primary">Add topic</button>
		{% endbuttons %}
		
	</form>
	

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/teacher.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ teacher }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_teacherMessage' teacher.id %}">Add new teacherMessage</a>
  </p>

  <ul>
  {% for teacherMessage in teacherMessages %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ teacherMessage.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_teacherMessage' teacherMessage.id %}">
            edit teacherMessage</a></small>
        <small><a href="{% url 'learning_logs:delete_teacherMessage' teacherMessage.id %}">
            delete teacherMessage</a></small>
      </h4>
      <div class="card-body">
        {{ teacherMessage.text|linebreaks }}
      </div>
    </div>
  {% empty %}
	<div class="alert alert-success" role="alert">
		There are no teacherMessage for this teacher yet!
	</div>
  {% endfor %}

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/teachers.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h1>Teachers</h1>
{% endblock page_header %}

{% block content %}
    {% for teacher in teachers %}
		<div class="card mb-3">
			<h4 class="card-header">
				{{ teacher.date_added|date:'M d,Y H:i' }}
			<small><a href="{% url 'learning_logs:new_teacher' %}">
					Add a new teacher</a></small>
			</h4>
			<div class="card-body">
				<a href="{% url 'learning_logs:teacher' teacher.id %}">{{ teacher }}</a>
			</div>
		</div>
    {% empty %}
	  <div class="alert alert-secondary" role="alert">
		No teachers have been added yet!
	  </div>
	  <h3><a href="{% url 'learning_logs:new_teacher' %}">Add a new teacher</a></h3>
    {% endfor %}

  <h3></h3>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

  <ul>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
            edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
	<div class="alert alert-success" role="alert">
		There are no entries for this topic yet!
	</div>
  {% endfor %}

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    {% for topic in topics %}
		<div class="card mb-3">
			<h4 class="card-header">
				{{ topic.date_added|date:'M d,Y H:i' }}
			<small><a href="{% url 'learning_logs:new_topic' %}">
					Add a new topic</a></small>
			</h4>
			<div class="card-body">
				<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</div>
		</div>
    {% empty %}
	  <div class="alert alert-secondary" role="alert">
		No topics have been added yet!
	  </div>
	  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>
    {% endfor %}

  <h3></h3>

{% endblock content %}